### ISSUE TITLE
Incorrect closing inline SVG elements after compilation with static-i18n

### ISSUE THREAD

**Issue by sergey-pimenov** [claudetech/node-static-i18n#20] opened 2018-01-01 20:52 UTC
Hi! This tool awesome, but I found strange bug: SVG elements like path lose closing '/' after compilation.
This problem also exist in gulp plugin.

Example.

This code:

```html
<!-- i18n -->
<h1 data-t="my.key"></h1>
<p data-t>other.key</p>
<input type="submit" data-attr-t value-t="other.ok">

<!-- Some inline SVG -->
<svg width="200" height="200">
      <path d="M10 10"/>
      <circle cx="10" cy="10" r="2" fill="red"/>
      <ellipse cx="60" cy="60" rx="50" ry="25"/>
</svg>
```

Will compiled to:

```html
<!-- i18n -->
<h1>Salut</h1>
<p>mec</p>
<input type="submit" value="confirmer">

<!-- Some inline SVG -->
<svg width="200" height="200">
      <path d="M10 10">
      <circle cx="10" cy="10" r="2" fill="red">
       <ellipse cx="60" cy="60" rx="50" ry="25">
</svg>
```

**[Link to example](https://drive.google.com/file/d/1cBmx05K16Wt__tEEgvJF3_tW5BV0GceA/view)**

It's not valid HTML and so it can cause some errors in browsers. It would be great if it's fixed.

**Comment by tuvistavie** [comment] 2018-01-03 18:09
The issue seems to come from https://github.com/fb55/htmlparser2
I added a `--xml` option, could you try to see if you get the output you expect when passing it please?
Thanks!

**Comment by sergey-pimenov** [comment] 2018-01-03 21:45
I try to repeate compile with your fix and unfortunately it's not work for me.

This:

```html
<html>
  <head>
    <title data-t data-t-interpolate>{{main.chapter}} 1</title>
    <script src="js/app.js"></script>
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 68 65">
      <path d="M14 27v-20c0-3.7-3.3-7-7-7s-7 3.3-7 7v41c0 8.2 9.2 17 20 17s20-9.2 20-20c0-13.3-13.4-21.8-26-18zm6 25c-3.9 0-7-3.1-7-7s3.1-7 7-7 7 3.1 7 7-3.1 7-7 7z"/>
    </svg>
  </body>
</html>
```
Compile to:

```html
<html>
  <head>
    <title>chapter 1</title>
    <script src="js/app.js"></script>
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 68 65">
      <path d="M14 27v-20c0-3.7-3.3-7-7-7s-7 3.3-7 7v41c0 8.2 9.2 17 20 17s20-9.2 20-20c0-13.3-13.4-21.8-26-18zm6 25c-3.9 0-7-3.1-7-7s3.1-7 7-7 7 3.1 7 7-3.1 7-7 7z">
    </svg>
  </body>
</html>
```

I'm not familiar with the syntax npm-scripts (before I used gulp plugin) so i tried several variants:

1. static-i18n --xml -l en -i en -i fr www
2. static-i18n --xml  true -l en -i en -i fr www
3. static-i18n --xml:true -l en -i en -i fr www
4. static-i18n --xml=true -l en -i en -i fr www

As I understand the first or second variant is correct, but I tried other varians too. Am I doing something wrong?

**Comment by tuvistavie** [comment] 2018-01-08 02:31
Thank you for the detailed report.
Sorry, it was my mistake.
It should now be fixed, please try to upgrade to the newest version.

**Comment by sergey-pimenov** [comment] 2018-01-09 10:38
Great job, thank you very much for your attention! Now everything works fine.
Do I understand correctly that Gulp and Grunt plugins automatically will use latest version of node-static-i18n?

**Comment by hohertz** [comment] 2018-01-09 17:12
Unfortunately, the problem is not solved with [Fix bug with xmlmode](https://github.com/claudetech/node-static-i18n/commit/c9dfa4df4fbea2b5456eadb2611128ef5a1cd550). As @tuvistavie has already written, the issue comes from [htmlparser2](https://github.com/fb55/htmlparser2). In short: Inline SVG should always be parsed with the XML option enabled even if the option is disabled for the rest of the HTML page.

There are already numerous issues in this respect, for example

- [svg parsing](https://github.com/fb55/htmlparser2/issues/79)

... and possibly a solution that has not yet been merged:

- [Use xmlmode for svg](https://github.com/fb55/htmlparser2/pull/129)

**Comment by connected** [comment] 2018-03-16 14:37
It's an issue with the [dom-serializer](https://github.com/cheeriojs/dom-serializer) that is used in [cheeriojs](https://github.com/cheeriojs/cheerio) module which is used in static-i18n to parse/modify DOM of the html source files.

I was able to fix this issue by forcing xml mode on svg tag children.

Please see [my PR](https://github.com/cheeriojs/dom-serializer/pull/74) for more details. Not sure if it will be merged, but it's worth a shot.

**Comment by osdiab** [comment] 2018-05-08 21:09
While `--xml` does fix the SVG tags, it also causes script tags to be self closing, which doesn't work and therefore causes my site to not render properly. Any thoughts?

**Comment by tuvistavie** [comment] 2018-05-12 02:31
@osdiab 
I think the workaround proposed by @connected is the best shot for now. Let's hope the PR gets merge.

**Comment by connected** [comment] 2018-10-23 18:49
I think this issue can be closed because it has been fixed since static-i18n updated cheerio dependency to v0.22.0. 

Be careful with the gulp package though, it still uses the old static-i18n version which has this SVG bug.

**Closed** 2018-11-10 11:52 UTC
